### PR TITLE
a few fixes

### PR DESCRIPTION
**Pull request by saejin-moon**
fixed references to my name/username to match the preferred lowercase stylin'.
spaced out division operations (`1 / ratio` iirc) for code cleanliness.

you had to one-up thumbnail.js, xD.
the hardest part with this script is seein' the changes you make to the thumbnail. do you have an idea other than constantly reloadin' the `/latest.png` of the program whenever you edit the thumbnail?

### CODE REVIEW

**Comment by HSstudent16** [comment]
Good to hear from you again, @thelegendski! :D

I dunno, re-writing the entire `document` element seems a little extreme...  besides, my version completely does away with the ancient `html2canvas` that Khan uses :P

You don't necessarily have to use a hidden canvas as the thumbnail source;  Do you think I should add an option to preview before saving?

**Comment by saejin-moon** [comment]
good to hear from you too, :D! hope to be back in the community tomorrow.

couldn't think of a better way to do it lol. curious to know how you did find `root.parent.WebpageOutput.prototype.getScreenshot`.

i sure would, :D! it makes the user experience much better, but i'm not sure how much hassle it would be. imho, i'd add a canvas with `display: fixed;` an' `z-index: 1000` to display the thumbnail when the user presses the escape key an' hides the thumbnail when the escape key is pressed again.

**Comment by astro-develops** [comment]
@HSstudent16 
I suggest adding preview users can toggle. Maybe like ctrl + esc can show them the preview. 

You don't need to show it to the users before every save otherwise it turns this into the same thing  many other thumbnail savers do on KA.

**Comment by HSstudent16** [comment]
### @thelegendski 
It's a bit of a long story, but I think it started with me looking through Khan's webpage environment source code on GH & the my browsers dev tools. Once I saw it was handled by `WebpageOutput`, I figured that it was probably leaked somehow into the coding environment, as with `PJSCodeInjector`, etc. in the PJS editor.

### @astro-develops
So does "following" me mean you can see everything I post, or were you just spying on this thread? xD

### @all
I think I'll add that soon :)

**Comment by saejin-moon** [comment]
@HSstudent16 
i believe Astro is currently watchin' this repo, so he sees any activity in it, =P.

**Comment by astro-develops** [comment]
@HSstudent16 
Nope. Not on GitHub. 
That's how it works on Replit (It's pretty annoying). 

As ski stated, I started watching this repo a couple of days ago. I tend to set watch activity to all, so I get notified every time there's a new release, a new pull request or issue is reported or when a new discussion is started. I saw ski's pull request and opened it to find this.

**Pull request merged**
